#ifndef LITE_SERVER_EMBED_H
#define LITE_SERVER_EMBED_H

#include <stddef.h>

/* One Lua file compiled into the binary; `path` is relative to data/
** (e.g. "server/init.lua"). The table is generated by cmake/embed_lua.cmake
** and ends with a NULL path. */
typedef struct {
  const char *path;
  const unsigned char *data;
  size_t len;
} lxs_embedded_module;

extern const lxs_embedded_module lxs_embedded_modules[];
extern const char lxs_embedded_build_id[];

#endif
