#ifndef THITHER_EMBED_H
#define THITHER_EMBED_H

#include <stddef.h>

/* One Lua file compiled into the binary; `path` is relative to data/
** (e.g. "thither/init.lua"). The table is generated by cmake/embed_lua.cmake
** and ends with a NULL path. */
typedef struct {
  const char *path;
  const unsigned char *data;
  size_t len;
} thither_embedded_module;

extern const thither_embedded_module thither_embedded_modules[];
extern const char thither_embedded_build_id[];

#endif
