-- Filesystem op tests: stat, readdir, read, write (atomic, etag conflict,
-- streamed), mkdir, remove, rename, realpath.
local H = require "harness"
local U = require "util"
local Client = require "client"
local mp = require "core.remote.msgpack"

local function connect(args)
  return Client.connect({ args = args })
end

H.test("fs: stat of file, dir, symlink and missing path", function()
  local dir = U.tmpdir("stat")
  U.write_file(dir .. "/f.txt", "hello\n")
  U.sh("mkdir " .. dir .. "/d && ln -s f.txt " .. dir .. "/l && ln -s nowhere " .. dir .. "/dangling && chmod 640 " .. dir .. "/f.txt")
  local c = connect()
  local f = c:request("stat", { path = dir .. "/f.txt" })
  H.eq(f.type, "file"); H.eq(f.size, 6); H.eq(f.mode, tonumber("640", 8))
  H.ok(f.etag:match("^%d+%-6%-%d+$"), "etag format mtime_ns-size-inode: " .. f.etag)
  H.eq(f.etag, f.mtime_ns .. "-6-" .. f.ino)
  H.ok(math.abs(f.mtime - os.time()) < 60)
  H.eq(c:request("stat", { path = dir .. "/d" }).type, "dir")
  local l = c:request("stat", { path = dir .. "/l" })
  H.eq(l.type, "file"); H.eq(l.is_link, true); H.eq(l.link, "f.txt"); H.eq(l.size, 6)
  l = c:request("stat", { path = dir .. "/l", nofollow = true })
  H.eq(l.type, "symlink")
  H.eq(c:request("stat", { path = dir .. "/dangling" }).type, "symlink")
  local _, err = c:request("stat", { path = dir .. "/missing" })
  H.eq(err.code, "ENOENT")
  _, err = c:request("stat", { path = dir .. "/f.txt/x" })
  H.eq(err.code, "ENOTDIR")
  c:close()
end)

H.test("fs: readdir returns stat info, sorted, with paging", function()
  local dir = U.tmpdir("readdir")
  for i = 1, 25 do U.write_file(string.format("%s/file%02d", dir, i), string.rep("x", i)) end
  U.sh("mkdir " .. dir .. "/adir && ln -s adir " .. dir .. "/zlink && ln -s nope " .. dir .. "/zdangling")
  local c = connect()
  local r = c:request("readdir", { path = dir })
  H.eq(r.total, 28); H.eq(#r.entries, 28); H.eq(r.more, false)
  H.eq(r.entries[1].name, "adir"); H.eq(r.entries[1].type, "dir")
  H.eq(r.entries[2].name, "file01"); H.eq(r.entries[2].size, 1)
  H.eq(r.entries[26].name, "file25"); H.eq(r.entries[26].size, 25)
  H.eq(r.entries[27].name, "zdangling"); H.eq(r.entries[27].type, "symlink")
  H.eq(r.entries[28].name, "zlink"); H.eq(r.entries[28].type, "dir"); H.eq(r.entries[28].link, "adir")
  H.ok(r.entries[2].etag)
  local p1 = c:request("readdir", { path = dir, offset = 0, limit = 10 })
  H.eq(#p1.entries, 10); H.eq(p1.more, true)
  local p3 = c:request("readdir", { path = dir, offset = 20, limit = 10 })
  H.eq(#p3.entries, 8); H.eq(p3.more, false); H.eq(p3.entries[1].name, "file20")
  local _, err = c:request("readdir", { path = dir .. "/file01" })
  H.eq(err.code, "ENOTDIR")
  _, err = c:request("readdir", { path = dir .. "/missing" })
  H.eq(err.code, "ENOENT")
  c:close()
end)

H.test("fs: readdir copes with a large directory", function()
  local dir = U.tmpdir("bigdir")
  U.sh("cd " .. dir .. " && seq 1 5000 | xargs touch")
  local c = connect()
  local r = c:request("readdir", { path = dir })
  H.eq(r.total, 5000); H.eq(#r.entries, 5000)
  c:close()
end)

H.test("fs: read ranges, EOF and binary content", function()
  local dir = U.tmpdir("read")
  local all = {}
  for i = 0, 255 do all[#all + 1] = string.char(i) end
  local data = string.rep(table.concat(all), 100)
  U.write_file(dir .. "/bin", data)
  local c = connect()
  local r = c:request("read", { path = dir .. "/bin", offset = 0, len = #data })
  H.ok(r.data == data, "full read"); H.eq(r.eof, true)
  r = c:request("read", { path = dir .. "/bin", offset = 1000, len = 500 })
  H.ok(r.data == data:sub(1001, 1500)); H.eq(r.eof, false)
  r = c:request("read", { path = dir .. "/bin", offset = #data - 10, len = 500 })
  H.eq(#r.data, 10); H.eq(r.eof, true)
  r = c:request("read", { path = dir .. "/bin", offset = #data + 100, len = 10 })
  H.eq(r.data, ""); H.eq(r.eof, true)
  local _, err = c:request("read", { path = dir .. "/bin", offset = 0, len = 9 * 1024 * 1024 })
  H.eq(err.code, "too_large")
  _, err = c:request("read", { path = dir, offset = 0, len = 10 })
  H.eq(err.code, "EISDIR")
  _, err = c:request("read", { path = dir .. "/bin", offset = 0, len = 10, etag = "1-2-3" })
  H.eq(err.code, "stale")
  c:close()
end)

H.test("fs: write creates, replaces atomically and preserves mode", function()
  local dir = U.tmpdir("write")
  local c = connect()
  local st = c:request("write", { path = dir .. "/new.txt", data = "one", mode = tonumber("600", 8) })
  H.eq(st.size, 3); H.eq(st.mode, tonumber("600", 8))
  H.eq(U.read_file(dir .. "/new.txt"), "one")
  H.eq(U.ls(dir), { "new.txt" }, "no temp file left behind")
  -- replacing keeps the existing mode regardless of the mode argument
  U.sh("chmod 755 " .. dir .. "/new.txt")
  local st2 = c:request("write", { path = dir .. "/new.txt", data = "two!", mode = tonumber("600", 8) })
  H.eq(st2.mode, tonumber("755", 8))
  H.eq(U.read_file(dir .. "/new.txt"), "two!")
  H.ok(st2.etag ~= st.etag)
  -- binary data
  local bin = {}
  for i = 0, 255 do bin[#bin + 1] = string.char(i) end
  bin = table.concat(bin):rep(50)
  c:request("write", { path = dir .. "/bin", data = mp.bin(bin) })
  H.ok(U.read_file(dir .. "/bin") == bin)
  -- empty file
  c:request("write", { path = dir .. "/empty", data = "" })
  H.eq(U.read_file(dir .. "/empty"), "")
  -- writing to a directory or missing parent fails
  local _, err = c:request("write", { path = dir, data = "x" })
  H.eq(err.code, "EISDIR")
  _, err = c:request("write", { path = dir .. "/no/such/dir/f", data = "x" })
  H.eq(err.code, "ENOENT")
  H.ok(c:request("write", { path = dir .. "/no/such/dir/f", data = "x", create_dirs = true }))
  H.eq(U.read_file(dir .. "/no/such/dir/f"), "x")
  H.eq(U.ls(dir .. "/no/such/dir"), { "f" })
  c:close()
end)

H.test("fs: write is atomic (readers see old or new, never partial)", function()
  local dir = U.tmpdir("atomic")
  local old = string.rep("A", 4 * 1024 * 1024)
  local new = string.rep("B", 4 * 1024 * 1024)
  U.write_file(dir .. "/f", old)
  local c = connect()
  local begin = c:request("write_begin", { path = dir .. "/f" })
  -- stream the new content in 256 KiB chunks: the target must stay untouched
  local ino_before = U.sh("stat -c %i " .. dir .. "/f")
  for off = 1, #new, 256 * 1024 do
    c:request("write_chunk", { wid = begin.wid, data = mp.bin(new:sub(off, off + 256 * 1024 - 1)) })
    H.ok(U.read_file(dir .. "/f") == old, "target changed before commit")
  end
  local temps = U.ls(dir)
  H.eq(#temps, 2, "one temp file while the write is open")
  local st = c:request("write_commit", { wid = begin.wid })
  H.eq(st.size, #new)
  H.ok(U.read_file(dir .. "/f") == new)
  H.eq(U.ls(dir), { "f" })
  H.ok(U.sh("stat -c %i " .. dir .. "/f") ~= ino_before, "replaced via rename")
  -- abort leaves the file as is and removes the temp file
  local b2 = c:request("write_begin", { path = dir .. "/f" })
  c:request("write_chunk", { wid = b2.wid, data = "partial" })
  H.ok(c:request("write_abort", { wid = b2.wid }))
  H.ok(U.read_file(dir .. "/f") == new)
  H.eq(U.ls(dir), { "f" })
  local _, err = c:request("write_commit", { wid = b2.wid })
  H.eq(err.code, "no_stream")
  -- a dropped connection mid-write leaves nothing behind
  local c2 = connect()
  local b3 = c2:request("write_begin", { path = dir .. "/f" })
  c2:request("write_chunk", { wid = b3.wid, data = "dangling" })
  c2:close()
  H.eq(U.ls(dir), { "f" })
  H.ok(U.read_file(dir .. "/f") == new)
  c:close()
end)

H.test("fs: if_match detects conflicts", function()
  local dir = U.tmpdir("etag")
  local c = connect()
  local st = c:request("write", { path = dir .. "/f", data = "v1", if_match = "-" })
  local _, err = c:request("write", { path = dir .. "/f", data = "v1b", if_match = "-" })
  H.eq(err.code, "conflict", "file exists but if_match is '-'")
  H.eq(err.etag, st.etag)
  H.eq(U.read_file(dir .. "/f"), "v1")
  local st2 = c:request("write", { path = dir .. "/f", data = "v2", if_match = st.etag })
  H.eq(U.read_file(dir .. "/f"), "v2")
  -- stale etag
  _, err = c:request("write", { path = dir .. "/f", data = "v3", if_match = st.etag })
  H.eq(err.code, "conflict")
  H.eq(err.etag, st2.etag)
  H.eq(U.read_file(dir .. "/f"), "v2")
  H.eq(U.ls(dir), { "f" }, "temp file removed after a conflict")
  -- out-of-band modification is detected (same size, new mtime)
  U.sh("sleep 0.05; printf v9 > " .. dir .. "/f")
  _, err = c:request("write", { path = dir .. "/f", data = "v4", if_match = st2.etag })
  H.eq(err.code, "conflict")
  -- deleted file
  U.sh("rm " .. dir .. "/f")
  _, err = c:request("write", { path = dir .. "/f", data = "v5", if_match = st2.etag })
  H.eq(err.code, "conflict"); H.eq(err.etag, "-")
  -- streamed writes honour if_match at commit time
  local cur = c:request("write", { path = dir .. "/g", data = "g1" })
  local b = c:request("write_begin", { path = dir .. "/g", if_match = cur.etag })
  c:request("write_chunk", { wid = b.wid, data = "g2" })
  U.sh("sleep 0.05; printf zz > " .. dir .. "/g")
  _, err = c:request("write_commit", { wid = b.wid })
  H.eq(err.code, "conflict")
  H.eq(U.read_file(dir .. "/g"), "zz")
  c:close()
end)

H.test("fs: write through a symlink keeps the link", function()
  local dir = U.tmpdir("symw")
  U.write_file(dir .. "/real", "old")
  U.sh("ln -s real " .. dir .. "/link")
  local c = connect()
  c:request("write", { path = dir .. "/link", data = "new" })
  H.eq(U.read_file(dir .. "/real"), "new")
  H.eq(U.sh("readlink " .. dir .. "/link"):gsub("%s+$", ""), "real")
  c:close()
end)

H.test("fs: mkdir, parents, remove, recursive remove", function()
  local dir = U.tmpdir("mk")
  local c = connect()
  H.ok(c:request("mkdir", { path = dir .. "/a" }))
  local _, err = c:request("mkdir", { path = dir .. "/a" })
  H.eq(err.code, "EEXIST")
  _, err = c:request("mkdir", { path = dir .. "/x/y/z" })
  H.eq(err.code, "ENOENT")
  H.ok(c:request("mkdir", { path = dir .. "/x/y/z", parents = true }))
  H.ok(c:request("mkdir", { path = dir .. "/x/y/z", parents = true }), "parents is idempotent")
  H.eq(c:request("stat", { path = dir .. "/x/y/z" }).type, "dir")
  U.write_file(dir .. "/x/y/z/f", "1")
  U.write_file(dir .. "/x/y/g", "2")
  U.sh("ln -s " .. dir .. "/a " .. dir .. "/x/linktoa")
  _, err = c:request("remove", { path = dir .. "/x" })
  H.eq(err.code, "ENOTEMPTY")
  H.ok(c:request("remove", { path = dir .. "/x", recursive = true }))
  H.ok(not U.exists(dir .. "/x/y/g"))
  H.eq(c:request("stat", { path = dir .. "/a" }).type, "dir", "recursive remove must not follow symlinks")
  H.ok(c:request("remove", { path = dir .. "/a" }), "empty dir")
  U.write_file(dir .. "/file", "1")
  H.ok(c:request("remove", { path = dir .. "/file" }))
  _, err = c:request("remove", { path = dir .. "/file" })
  H.eq(err.code, "ENOENT")
  _, err = c:request("remove", { path = "/", recursive = true })
  H.eq(err.code, "EINVAL")
  c:close()
end)

H.test("fs: rename and realpath and home", function()
  local dir = U.tmpdir("mv")
  U.write_file(dir .. "/a", "A")
  U.write_file(dir .. "/b", "B")
  local c = connect()
  H.ok(c:request("rename", { from = dir .. "/a", to = dir .. "/c" }))
  H.eq(U.read_file(dir .. "/c"), "A")
  local _, err = c:request("rename", { from = dir .. "/a", to = dir .. "/d" })
  H.eq(err.code, "ENOENT")
  _, err = c:request("rename", { from = dir .. "/c", to = dir .. "/b", overwrite = false })
  H.eq(err.code, "EEXIST")
  H.eq(U.read_file(dir .. "/b"), "B")
  H.ok(c:request("rename", { from = dir .. "/c", to = dir .. "/b" }), "overwrite is the default")
  H.eq(U.read_file(dir .. "/b"), "A")
  U.sh("mkdir " .. dir .. "/real && ln -s real " .. dir .. "/sym")
  H.eq(c:request("realpath", { path = dir .. "/sym/../real" }), dir .. "/real")
  _, err = c:request("realpath", { path = dir .. "/missing" })
  H.eq(err.code, "ENOENT")
  H.eq(c:request("home"), os.getenv("HOME"))
  c:close()
end)

H.test("fs: stat/read of unreadable paths report EACCES", function()
  if U.sh("id -u"):match("^0") then return end  -- root ignores permissions
  local dir = U.tmpdir("acc")
  U.write_file(dir .. "/secret", "s")
  U.sh("chmod 000 " .. dir .. "/secret")
  local c = connect()
  local _, err = c:request("read", { path = dir .. "/secret", offset = 0, len = 1 })
  H.eq(err.code, "EACCES")
  c:close()
  U.sh("chmod 600 " .. dir .. "/secret")
end)

H.test("cleanup: fs tests", function() U.cleanup() end)
