# Generates the C file that embeds the server's Lua modules into lite-xl-server.
#
#   cmake -DOUT=<file.c> -DROOT=<data dir> -DFILES=<a.lua|b/c.lua|...> -DVERSION=<v> -P embed_lua.cmake
#
# FILES are paths relative to ROOT, separated by "|" (a ";" list cannot be
# passed through add_custom_command). Each file becomes a byte array; the table
# `lxs_embedded_modules` maps the relative path to it (see src/server/embed.c).
# `lxs_embedded_build_id` is the first 12 hex digits of a SHA-256 over VERSION
# and every path and file hash, so it changes whenever an embedded file does.
# The output is only rewritten when its content changes.

string(REPLACE "|" ";" _files "${FILES}")
set(_arrays "")
set(_table "")
set(_hash_input "${VERSION}")
set(_i 0)
# CMake regexes have no {n}: one output line is 16 explicit byte patterns
string(REPEAT "0x[0-9a-f][0-9a-f]," 16 _line)
foreach(_rel IN LISTS _files)
    if(_rel STREQUAL "")
        continue()
    endif()
    # CRLF -> LF, so a Windows checkout embeds (and hashes) the same bytes
    file(READ "${ROOT}/${_rel}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    set(_tmp "${OUT}.tmp")
    file(WRITE "${_tmp}" "${_text}")
    file(READ "${_tmp}" _hex HEX)
    file(REMOVE "${_tmp}")
    string(SHA256 _sum "${_text}")
    string(APPEND _hash_input "\n${_rel}\n${_sum}")
    string(LENGTH "${_hex}" _n)
    math(EXPR _len "${_n} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "(${_line})" "\\1\n" _bytes "${_bytes}")
    # trailing NUL: keeps empty files valid C; not counted in the length
    string(APPEND _arrays "/* ${_rel} */\nstatic const unsigned char m${_i}[] = {\n${_bytes}0x00\n};\n\n")
    string(APPEND _table "  { \"${_rel}\", m${_i}, ${_len} },\n")
    math(EXPR _i "${_i} + 1")
endforeach()

if(_i GREATER 0)
    string(SHA256 _build_id "${_hash_input}")
    string(SUBSTRING "${_build_id}" 0 12 _build_id)
else()
    set(_build_id "")
endif()

set(_content "/* Generated by cmake/embed_lua.cmake from data/. Do not edit. */
#include <stddef.h>
#include \"embed.h\"

${_arrays}const lxs_embedded_module lxs_embedded_modules[] = {
${_table}  { NULL, NULL, 0 }
};

const char lxs_embedded_build_id[] = \"${_build_id}\";
")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
