-- Mount-root path forms and the common.* / Project helpers on them.
return function(T)
  local paths = require "core.remote.paths"
  local common = require "core.common"
  local WIN = PATHSEP == "\\"

  T.test("paths: make / parse / is_remote", function()
    local p = paths.make("devbox", "/home/u/proj/src/a.lua")
    T.eq(p, WIN and "\\\\lxl-remote\\devbox\\home\\u\\proj\\src\\a.lua" or "/.lxl-remote/devbox/home/u/proj/src/a.lua")
    local host, rpath = paths.parse(p)
    T.eq(host, "devbox")
    T.eq(rpath, "/home/u/proj/src/a.lua")
    T.ok(paths.is_remote(p))
    T.ok(not paths.is_remote("/home/u"))
    T.ok(not paths.is_remote("C:\\x\\y"))
    T.ok(not paths.is_remote(nil))
    T.ok(not paths.is_remote(""))
    T.ok(not paths.is_remote("relative/path"))
    if WIN then
      T.ok(paths.is_remote("//lxl-remote/devbox/home/u"), "forward slashes")
      T.eq(select(2, paths.parse("//lxl-remote/devbox/home/../etc")), "/etc")
      T.ok(paths.is_remote("\\\\LXL-REMOTE\\devbox\\x"), "case insensitive")
    end
    T.eq(select(2, paths.parse(paths.make("h", "/a/./b/../c//d"))), "/a/c/d")
    T.eq(paths.host_root("h"), WIN and "\\\\lxl-remote\\h\\" or "/.lxl-remote/h")
    T.eq(select(2, paths.parse(paths.host_root("h"))), "/")
    T.eq(paths.dirname(p), paths.make("devbox", "/home/u/proj/src"))
    T.eq(paths.dirname(paths.make("devbox", "/x")), paths.make("devbox", "/"))
    T.eq(paths.dirname(paths.make("devbox", "/")), nil)
    T.eq(paths.basename(p), "a.lua")
    T.eq(paths.join(paths.make("h", "/a"), "b"), paths.make("h", "/a/b"))
    T.eq(paths.join(paths.make("h", "/"), "b"), paths.make("h", "/b"))
  end)

  T.test("paths: hosts and locations", function()
    T.eq(paths.sanitize_host("wsl:"), "wsl")
    T.eq(paths.sanitize_host("wsl:Ubuntu"), "wsl-Ubuntu")
    T.eq(paths.sanitize_host("me@box"), "me@box")
    T.eq(paths.sanitize_host("my session"), "my-session")
    local h, p = paths.split_location("devbox:/home/u")
    T.eq(h, "devbox"); T.eq(p, "/home/u")
    h, p = paths.split_location("wsl:/tmp")
    T.eq(h, "wsl"); T.eq(p, "/tmp")
    h, p = paths.split_location("wsl:Ubuntu:/tmp/x")
    T.eq(h, "wsl:Ubuntu"); T.eq(p, "/tmp/x")
    h, p = paths.split_location("me@box:~/code")
    T.eq(h, "me@box"); T.eq(p, "~/code")
    h, p = paths.split_location("justahost")
    T.eq(h, "justahost"); T.eq(p, nil)
  end)

  T.test("paths: common.* helpers accept remote paths", function()
    local root = paths.make("devbox", "/home/u/proj")
    local file = paths.make("devbox", "/home/u/proj/src/a.lua")
    T.eq(common.normalize_path(file), file)
    T.eq(common.normalize_path(root .. PATHSEP .. "src" .. PATHSEP .. ".." .. PATHSEP .. "src" .. PATHSEP .. "a.lua"), file)
    T.ok(common.is_absolute_path(file))
    T.ok(common.path_belongs_to(file, root))
    T.ok(not common.path_belongs_to(paths.make("devbox", "/home/u/proj2/x"), root))
    T.ok(not common.path_belongs_to(paths.make("other", "/home/u/proj/src/a.lua"), root))
    T.eq(common.relative_path(root, file), "src" .. PATHSEP .. "a.lua")
    T.eq(common.basename(file), "a.lua")
    T.eq(common.dirname(file), paths.make("devbox", "/home/u/proj/src"))
    T.eq(common.relative_path(root, root), ".")
    T.eq(common.relative_path(root, paths.make("devbox", "/home/u")), ".." .. PATHSEP)
  end)

  T.test("paths: host root and UNC quirks (patches A/B)", function()
    if not WIN then return end
    -- Patch A: a share root without trailing separator is a volume
    T.eq(common.normalize_path("\\\\lxl-remote\\h"), "\\\\lxl-remote\\h\\")
    T.eq(common.normalize_path("\\\\lxl-remote\\h\\"), "\\\\lxl-remote\\h\\")
    T.eq(common.normalize_path("//lxl-remote/h/x/../y"), "\\\\lxl-remote\\h\\y")
    -- unchanged for drives
    T.eq(common.normalize_path("C:\\"), "C:\\\\")
    T.eq(common.normalize_path("c:/a/b/.."), "C:\\a")
    -- the dirname of a file directly in the remote root is the host root
    local f = paths.make("h", "/etc")
    T.eq(common.normalize_path(common.dirname(f)), "\\\\lxl-remote\\h\\")
    -- Patch B: different shares / drives are different volumes
    T.eq(common.relative_path(paths.make("h", "/a"), "C:\\Windows"), "C:\\Windows")
    T.eq(common.relative_path("C:\\x", paths.make("h", "/a")), paths.make("h", "/a"))
    T.eq(common.relative_path(paths.make("h", "/a"), paths.make("g", "/a")), paths.make("g", "/a"))
    T.eq(common.relative_path("\\\\srv\\share\\a", "\\\\srv\\share\\a\\b\\c"), "b\\c")
  end)

  T.test("paths: Project on a remote root", function()
    local Project = require "core.project"
    local root = paths.make("devbox", "/home/u/proj")
    local pr = Project(root)
    T.eq(pr.name, "proj")
    local file = paths.make("devbox", "/home/u/proj/src/a.lua")
    T.eq(pr:normalize_path(file), "src" .. PATHSEP .. "a.lua")
    T.eq(pr:absolute_path("src" .. PATHSEP .. "a.lua"), root .. PATHSEP .. "src" .. PATHSEP .. "a.lua")
    local other = paths.make("devbox", "/etc/hosts")
    T.eq(pr:normalize_path(other), other)
    T.eq(pr:normalize_path(paths.make("other", "/home/u/proj/src/a.lua")), paths.make("other", "/home/u/proj/src/a.lua"))
  end)
end
