-- io.open / io.lines / loadfile / dofile on remote files; atomic write and etag conflicts.
return function(T)
  local paths = require "plugins.thither.paths"

  T.test("io: read modes, lines, seek, loadfile", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    T.sh_ok("cd " .. dir .. " && printf 'line1\\nline2\\r\\nlast' > t.txt && printf 'return { a = 1, b = \"x\" }\\n' > cfg.lua")
    local f = paths.join(m, "t.txt")
    local fp = T.ok(io.open(f, "rb"))
    T.eq(io.type(fp), "file")
    T.eq(fp:read("l"), "line1")
    T.eq(fp:read("L"), "line2\r\n")
    T.eq(fp:read(2), "la")
    T.eq(fp:read("a"), "st")
    T.eq(fp:read("a"), "")
    T.eq(fp:read("l"), nil)
    T.eq(fp:seek("set", 0), 0)
    T.eq(fp:read(5), "line1")
    T.eq(fp:seek("cur"), 5)
    T.eq(fp:seek("end"), 17)
    fp:close()
    T.eq(io.type(fp), "closed file")
    local lines = {}
    for l in io.lines(f) do lines[#lines + 1] = l end
    T.eq(#lines, 3); T.eq(lines[3], "last")
    local fp2 = T.ok(io.open(f, "r"))
    local n = 0
    for _ in fp2:lines() do n = n + 1 end
    fp2:close()
    T.eq(n, 3)
    local cfg = dofile(paths.join(m, "cfg.lua"))
    T.eq(cfg.a, 1); T.eq(cfg.b, "x")
    local fn = T.ok(loadfile(paths.join(m, "cfg.lua")))
    T.eq(fn().a, 1)
    local nofn, err = loadfile(paths.join(m, "missing.lua"))
    T.eq(nofn, nil); T.ok(err:find("No such file"), err)
    local nofp, err2, code = io.open(paths.join(m, "missing.txt"), "rb")
    T.eq(nofp, nil); T.eq(code, 2)
    T.fails(function() io.lines(paths.join(m, "missing.txt")) end, "No such file")
    local d, derr, dcode = io.open(m, "rb")
    T.eq(d, nil); T.eq(dcode, 21)
  end)

  T.test("io: a multi-megabyte file reads back byte-exact", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    T.sh_ok("head -c 5000000 /dev/urandom > " .. dir .. "/rnd.bin && md5sum " .. dir .. "/rnd.bin > " .. dir .. "/rnd.md5")
    local expect = T.sh_ok("cut -d' ' -f1 " .. dir .. "/rnd.md5"):gsub("%s+", "")
    local fp = T.ok(io.open(paths.join(m, "rnd.bin"), "rb"))
    local data = fp:read("a")
    fp:close()
    T.eq(#data, 5000000)
    -- md5 on the server side of what we received
    local back = paths.join(m, "copy.bin")
    local w = T.ok(io.open(back, "wb"))
    w:write(data)
    T.eq(w:close(), true)
    local got = T.sh_ok("md5sum " .. dir .. "/copy.bin | cut -d' ' -f1"):gsub("%s+", "")
    T.eq(got, expect)
  end)

  T.test("io: write is atomic and leaves no temp files", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    local f = paths.join(m, "w.txt")
    local fp = T.ok(io.open(f, "wb"))
    fp:write("one ", 2, " three")
    T.eq(fp:seek("end"), 11)
    T.eq(fp:close(), true)
    T.eq(T.sh_ok("cat " .. dir .. "/w.txt"), "one 2 three")
    T.eq(system.get_file_info(f).size, 11)
    T.eq(T.sh_ok("ls -A " .. dir):gsub("%s+$", ""), "w.txt")
    -- mode is kept for existing files
    T.sh_ok("chmod 600 " .. dir .. "/w.txt")
    local fp2 = T.ok(io.open(f, "wb"))
    fp2:write("replaced")
    fp2:close()
    T.eq(T.sh_ok("stat -c %a " .. dir .. "/w.txt"):gsub("%s+", ""), "600")
    -- append
    local fp3 = T.ok(io.open(f, "ab"))
    fp3:write("+more")
    fp3:close()
    T.eq(T.sh_ok("cat " .. dir .. "/w.txt"), "replaced+more")
    -- r+b is refused so Doc:save falls back to wb
    T.eq(io.open(f, "r+b"), nil)
    -- writing into a missing directory fails with a clear error and no file
    local bad = T.ok(io.open(paths.join(m, "nodir/x"), "wb"))
    local ok, err = bad:close()
    T.eq(ok, nil); T.ok(err:find("No such file"), err)
  end)

  T.test("io: write conflicts when the server file changed", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    T.sh_ok("printf 'original' > " .. dir .. "/c.txt")
    local f = paths.join(m, "c.txt")
    local r = T.ok(io.open(f, "rb"))
    T.eq(r:read("a"), "original")
    r:close()
    T.sh_ok("sleep 0.05; printf 'changed on the server' > " .. dir .. "/c.txt")
    local w = T.ok(io.open(f, "wb"))
    w:write("my version")
    local ok, err, code = w:close()
    T.eq(ok, nil)
    T.ok(err:find("conflict"), err)
    T.eq(T.sh_ok("cat " .. dir .. "/c.txt"), "changed on the server")
    -- after reading the new version the write goes through
    local r2 = T.ok(io.open(f, "rb"))
    r2:read("a"); r2:close()
    local w2 = T.ok(io.open(f, "wb"))
    w2:write("my version")
    T.eq(w2:close(), true)
    T.eq(T.sh_ok("cat " .. dir .. "/c.txt"), "my version")
    -- our own writes keep the known etag current: a second write needs no re-read
    local w3 = T.ok(io.open(f, "wb"))
    w3:write("again")
    T.eq(w3:close(), true)
  end)

  T.test("io: large write goes through write_begin/chunk/commit", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    local data = string.rep("0123456789abcdef", 1024 * 1024)   -- 16 MiB
    local w = T.ok(io.open(paths.join(m, "big.txt"), "wb"))
    w:write(data)
    T.eq(w:close(), true)
    T.eq(tonumber((T.sh_ok("stat -c %s " .. dir .. "/big.txt"):gsub("%s+", ""))), #data)
    T.eq(T.sh_ok("md5sum < " .. dir .. "/big.txt"):sub(1, 32), T.sh_ok("head -c 16777216 /dev/null; yes 0123456789abcdef | tr -d '\\n' | head -c 16777216 | md5sum"):sub(1, 32))
  end)

  T.test("io: blocking io inside a core thread", function()
    local h = T.connect()
    local dir, m = T.tmpdir()
    local f = paths.join(m, "thr.txt")
    T.in_thread(function()
      local w = io.open(f, "wb")
      w:write("from a thread")
      assert(w:close())
      local r = io.open(f, "rb")
      local s = r:read("a")
      r:close()
      assert(s == "from a thread", s)
      assert(system.get_file_info(f).size == 13)
    end)
  end)
end
